### ISSUE TITLE
Explicitly state in the README that storing data in session is unsafe

### ISSUE THREAD

**Issue by catamphetamine** [DaAwesomeP/koa-session-redis3#7]
``` javascript
    try {
      yield *next;
    } catch (err) {
      throw err;
    } finally {
      if (sess.changed(json)) {
        // save
        json = sess.save();
        yield client.set(redisOption.keySchema + sid, json);
        client.ttl(redisOption.keySchema + sid);
      }
    }
```

This code will break under race conditions.
You should state it explicitly in the documentation so that users don't rely on the session store to be consistent.

**Comment by DaAwesomeP** [comment]
@halt-hammerzeit I'm sorry, but I don't understand what's wrong with this code. Could you please explain?

**Comment by catamphetamine** [comment]
When you do `yield` it ceases operation and allows other requests of the same session to be processed. Those other requests can modify the session too, and finish earlier than this one. And their changes to the session will be lost after this request overrites them.

**Comment by DaAwesomeP** [comment]
I see. Well, I now help maintain `koa-redis`, which works alongside `koa-generic-session`, and I'm migrating to it. I'm about to deprecate this repo.

I'm not really sure how to fix this. If the request system were synchronous, and each request would have to wait for the previous one to complete. While that would fix this issue, it would be detrimental to the speed of the server. I also can't see why this wouldn't be a problem with a simple cookie-based store or even something in another language (i.e. PHP).

Also, Redis is _fast_. If you're having this issue, then you really need to examine how many requests you're making to your app, as it my be borderline fatal if the amount of traffic were to scale up.

Thank you for opening an issue.

**Comment by catamphetamine** [comment]
It's difficult to find a way fix it that's for sure. That's why i'm not proposing a solution. I'm stating the fact.

If you migrated to `koa-redis` then I should probably too

**Comment by DaAwesomeP** [comment]
Yeah this repo doesn't offer as many features and isn't nearly as well maintained as `koa-generic-redis` is.

You could try adding a timestamp of some sort to the session. What you really need in this case is a request queue that is sorted by session ID. But again, you'd lose a lot of speed.

**Comment by catamphetamine** [comment]
@DaAwesomeP ok, I've already switched to `generic-session`, that was quick and smooth.

I'm not having any issues.
I'm sheding the light on possible issues for an abstract use case.
